# Lab 2: Similarity and Distance Metrics

In this lab you will complete implementations of the edit distance (a.k.a Levenshtein distance) and Euclidean distance metrics.

## Edit Distance

In [117]:
import numpy as np
import math

def edit_distance(w1, w2):
    w1 = "#" + w1
    w2 = "#" + w2
    
    # create matrix, initially filled with zeros
    mat = np.zeros((len(w1), len(w2))) 
    
    # fill first row
    for i in range(0, len(w2)):
        mat[0,i] = i
        
    # fill first column
    for i in range(0, len(w1)):
        mat[i,0] = i
        
    
    # fill in the rest
    # TO-DO:
    
  
    for i in range(1, len(w1)): # for-loop iterating over row 1 up to length of word 1 (word on top of matrix)
        for j in range(1, len(w2)): # nested for-loop iterating over column 1 up to length of word 2 (word on left of matrix)
            
            w1_char = w1[i]
            w2_char = w2[j]
            
            if (w1_char == w2_char):
                mat[i,j] = min(mat[i,j-1], mat[i-1,j], mat[i-1,j-1]) + 0 # case for characters being equal
                
            else:
                mat[i,j] = min(mat[i,j-1], mat[i-1,j], mat[i-1,j-1]) + 1 # case for characters not being equal
                
                
    # just display the matrix - 
    # no need to return anything
    print(mat)
    print("Above is the edit distance matrix for the two strings. \n")
    print("The edit distance between " + w1[1:] + " and " + w2[1:] + " is " + str(mat[len(w1)-1, len(w2)-1]))


Then call your function:

In [169]:
edit_distance("dave", "dve")

[[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 1. 2.]
 [3. 2. 1. 2.]
 [4. 3. 2. 1.]]
Above is the edit distance matrix for the two strings 

The edit distance between dave and dve is 1.0


# Euclidean Distance

Write a function euclidean() that takes two vectors and returns their Euclidean distance. 

In [174]:
def euclidean(v1, v2):
    print("calculating euclidean distance between the vectors...")
    # fill in the rest
    # TO-DO
    
    summation = 0
    
    for i in range(0, max(len(v1), len(v2))):
        summation += (v1[i] - v2[i])**2
    
    # return the euclidean distance score
    return math.sqrt(summation)
    
    
    

Then call your function:

In [175]:
v = np.matrix([[4], [3], [2], [1]])
u = np.matrix([[1], [2], [3], [4]])

score1 = euclidean(v,u)
print(score1)
print()
# should be 4.47213595499958

score2 = euclidean(v,v)
print(score2)
print()
# should be 0.0

score3 = euclidean(u,u)
print(score3)
# should be 0.0

calculating euclidean distance between the vectors...
4.47213595499958

calculating euclidean distance between the vectors...
0.0

calculating euclidean distance between the vectors...
0.0


# Hints for Completing the Euclidean Distance Implementation

* It is possible to implement the function without the use of loops. 
* To calculate the difference between two vectors, just use the - (minus) symbol. 
* If you imported numpy as np, then you can use np.square() to square the elements of a vector. 
* For taking a square root, use math.sqrt(). 
* If the vectors are not the same length, just truncate the longer one so that they are the same length. 


## __Deliverable__: Submit your completed notebook via Blackboard.