# COMP 455

# Lab 4: PageRank

In [ ]:
import numpy as np 

This is the example transition matrix from the lecture:

In [63]:
M = np.matrix([[0, 1/2, 0, 0], [1/3, 0, 0, 1/2],  [1/3, 0, 1, 1/2],  [1/3, 1/2, 0, 0]])
print(M)

[[ 0.          0.5         0.          0.        ]
 [ 0.33333333  0.          0.          0.5       ]
 [ 0.33333333  0.          1.          0.5       ]
 [ 0.33333333  0.5         0.          0.        ]]


And here is our initial vector:

In [ ]:
v = np.matrix([[0.25], [0.25], [0.25], [0.25]])
print(v)

And here is how we can multiply them, representing one step by our random surfer:


In [ ]:
print(M*v)

# Lab Assignment

Finish an implementation of this running example from the lecture:

* For taxation, use a  value of 0.8. 
* Multiply the transition matrix by that value. 
* Create a vector representing the tax term (see slide 33 from lecture). 
* Write a for loop that does 20 steps of the random surfer, using the tax term in the updates. 
* Show the resulting vector after 20 steps. 

The state vector after 20 steps should be close to this:

[[ 0.10135484]
 [ 0.12838347]
 [ 0.64187822]
 [ 0.12838347]]


In [75]:
import numpy as np

M = np.matrix([[0, 1/2, 0, 0], [1/3, 0, 0, 1/2],  [1/3, 0, 1, 1/2],  [1/3, 1/2, 0, 0]])
print("M = \n", M)
print()

v = np.matrix([[0.25], [0.25], [0.25], [0.25]])
print("v = \n", v)
print()


beta = 0.8
M = M*beta
print("M*beta = \n", M)
print()

e = np.matrix([[1],[1],[1],[1]])
n = 4
tax_term = (1 - beta)*(e/n)
print("taxation term = \n", tax_term)
print()

resultant_v = v
for i in range(20):
    resultant_v = M*resultant_v + tax_term

print("Resultant vector = \n", resultant_v)

M = 
 [[ 0.          0.5         0.          0.        ]
 [ 0.33333333  0.          0.          0.5       ]
 [ 0.33333333  0.          1.          0.5       ]
 [ 0.33333333  0.5         0.          0.        ]]

v = 
 [[ 0.25]
 [ 0.25]
 [ 0.25]
 [ 0.25]]

M*beta = 
 [[ 0.          0.4         0.          0.        ]
 [ 0.26666667  0.          0.          0.4       ]
 [ 0.26666667  0.          0.8         0.4       ]
 [ 0.26666667  0.4         0.          0.        ]]

taxation term = 
 [[ 0.05]
 [ 0.05]
 [ 0.05]
 [ 0.05]]

Resultant vector = 
 [[ 0.10135339]
 [ 0.12838135]
 [ 0.64188392]
 [ 0.12838135]]
